### ISSUE TITLE
FF-HEDM workflow enhancements

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#952]
User feedback (thanks @minety, @georgejoe) has made it clear that we need a bit more feedback during the indexing and fitting processes.  Here is a running list (with some existing issues linked) encapsulating some of the highest priority needs:

- Indexing (`find-orientations`):
  - [x] Add ability to store/save the scored orientation list (like CLI); would also be nice to report stats on scores. (fixed by #966)
  - [x] Add ability to expose the quaternion grid search option (_i.e.,_ load a npy file of quaternions to test rather than using the seeded search) (fixed by #966)
  - [x] Report how many test orientations are generated in the seeded search process and issue a warning if that number exceeds 5e7 quaternions (fixed by #966)
  - [x] Report how many orientations are staged for clustering and issue a warning dialog if that number exceeds 1e6 (parameters are likely not ideal and this can overwhelm the memory in `dbscan`) (fixed by #966)
  - [x] Expose the ability to re-run the clustering step on scored orientations with new parameters, including ability to load a list of scored orientations (clobbering the results of `paintGrid`) (tracked in #968)
  - [ ] Add the ability to plot indexing results on the eta-ome maps (fixed by #1180)
- Fitting (`fit-grains`)
  - [x] Add ability to visualize spots to fit grains results dialog (tracked in #945)
  - [x] Add an option to the FitGrainsOptionsDialog to write out spots files (tracked in #944)
  - [x] Add spot tolerance viz to rotation series overlays (tracked in #386) to assist users in setting them

@psavery -- do we need to pull someone else in to help here?

**Comment by joelvbernier** [comment]
@psavery -- added another functionality to the `find-orientations` enhancements above; should I convert that item to a separate issue?

**Comment by psavery** [comment]
@joelvbernier No this is fine!
